openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: tforster8@my.bcit.ca
paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets mail_ID and address of sent mail
      responses:
        '200':
          description: Successfully returned a list of address'
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/sendmail'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    sendmail:
      type: object
      required:
        - mail_ID
        - address
      properties:
        mail_ID:
          type: string
          format: uuid
          example: 371f1ee-6c54-4c95-90e6-d701748f0851
        address:
          type: string
          example: '112233 Homer Av'
