openapi: 3.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Receives letters being posted and post letters
  contact:
    email: tasman.forster@gmail.com
tags:
  - name: Devices
    description: operations for recieveing letters
paths:
  /post-office/send:
    post:
      tags:
        - Devices
      summary: sends mail
      operationId: app.send_mail
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendmail'
        description: sends mail
  /post-office/recievemail:
    post:
      tags:
        - Devices
      summary: recieves mail
      operationId: app.recieve_mail
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/recievemail'
        description: Recieves mail
components:
  schemas:
    sendmail:
      type: object
      required:
        - mail_ID
        - address
      properties:
        mail_ID:
          type: string
          format: uuid
          example: 371f1ee-6c54-4c95-90e6-d701748f0851
        address:
          type: string
          example: '112233 Homer Av'
    recievemail:
      required:
        - mail_ID
        - address
      properties:
        mail_ID:
          type: string
          format: uuid
          example: 696f1cc-6c54-4b01-90e6-d701748f0851
        address:
          type: string
          example: '123 Seaseme street'
      type: object